import { z } from "zod";

export const AerolineasFlightData = z.object({
  id: z.string(),
  stda: z.string(),
  arpt: z.string(),
  idaerolinea: z.string(),
  aerolinea: z.string(),
  mov: z.string(),
  nro: z.string(),
  logo: z.string(),
  destorig: z.string(),
  IATAdestorig: z.string(),
  etda: z.string(),
  atda: z.string(),
  sector: z.string(),
  termsec: z.string(),
  gate: z.string(),
  estes: z.string(),
  estin: z.string(),
  estbr: z.string(),
  color: z.string(),
  matricula: z.string(),
  chk_from: z.string().nullable(),
  chk_to: z.string().nullable(),
  belt: z.string(),
  chk_lyf: z.string().nullable(),
  sdtempunit: z.string().nullable(),
  sdtemp: z.union([z.string(), z.number()]).nullable(),
  sdphrase: z.string().nullable(),
  idclimaicono: z.union([z.string(), z.number()]).nullable(),
  tipoVuelo: z.string().nullable(),
  id_flight_tp: z.string(),
  id_flight_tra: z.string(),
  id_flight_reg: z.string(),
  idshared: z.string(),
  acftype: z.string().nullable(),
  pasajeros: z.string(),
  posicion: z.string(),
  term: z.string().nullable(),
  checkins: z.string(),
  via: z.string(),
  blockon: z.string(),
  blockoff: z.string(),
  acft_body: z.string(),
  rot: z.string(),
});
