import { z } from "zod";

export const AerolineasFlightData = z.object({
  id: z.string(),
  stda: z.string(),
  arpt: z.string(),
  idaerolinea: z.string(),
  aerolinea: z.string(),
  mov: z.string(),
  nro: z.string(),
  logo: z.string(),
  destorig: z.string(),
  IATAdestorig: z.string(),
  etda: z.string(),
  atda: z.string(),
  sector: z.string(),
  termsec: z.string(),
  gate: z.string(),
  estes: z.string(),
  estin: z.string(),
  estbr: z.string(),
  color: z.string(),
  matricula: z.string(),
  chk_from: z.null(),
  chk_to: z.null(),
  belt: z.string(),
  chk_lyf: z.null(),
  sdtempunit: z.null(),
  sdtemp: z.null(),
  sdphrase: z.null(),
  idclimaicono: z.null(),
  tipoVuelo: z.null(),
  id_flight_tp: z.string(),
  id_flight_tra: z.string(),
  id_flight_reg: z.string(),
  idshared: z.string(),
  acftype: z.null(),
  pasajeros: z.string(),
  posicion: z.string(),
  term: z.null(),
  checkins: z.string(),
  via: z.string(),
  blockon: z.string(),
  blockoff: z.string(),
  acft_body: z.string(),
  rot: z.string(),
});
